site_name: Multiplayer Stamina Docs
site_author: Spyderweb Studios Ltd
site_favicon: "/assets/Logos/SpyderwebLogo.png"

theme:
  name: readthedocs
  nav_style: dark
  logo: "/assets/Logos/SpyderwebBanner.png"


plugins:
  - awesome-pages